
python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x '../data/cora/x_np.pkl' --path_edge_index '../data/cora/edge_index_np.pkl' --path_y '../data/cora/y_np.pkl' --path_save './result_distribution/cora_gcn.json'
python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x '../data/cora/x_np.pkl' --path_edge_index '../data/cora/edge_index_np.pkl' --path_y '../data/cora/y_np.pkl' --path_save './result_distribution/cora_gat.json'
python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x '../data/cora/x_np.pkl' --path_edge_index '../data/cora/edge_index_np.pkl' --path_y '../data/cora/y_np.pkl' --path_save './result_distribution/cora_graphsage.json'
python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x '../data/cora/x_np.pkl' --path_edge_index '../data/cora/edge_index_np.pkl' --path_y '../data/cora/y_np.pkl' --path_save './result_distribution/cora_tagcn.json'

python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x '../data/citeseer/x_np.pkl' --path_edge_index '../data/citeseer/edge_index_np.pkl' --path_y '../data/citeseer/y_np.pkl' --path_save './result_distribution/citeseer_gcn.json'
python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x '../data/citeseer/x_np.pkl' --path_edge_index '../data/citeseer/edge_index_np.pkl' --path_y '../data/citeseer/y_np.pkl' --path_save './result_distribution/citeseer_gat.json'
python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x '../data/citeseer/x_np.pkl' --path_edge_index '../data/citeseer/edge_index_np.pkl' --path_y '../data/citeseer/y_np.pkl' --path_save './result_distribution/citeseer_graphsage.json'
python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x '../data/citeseer/x_np.pkl' --path_edge_index '../data/citeseer/edge_index_np.pkl' --path_y '../data/citeseer/y_np.pkl' --path_save './result_distribution/citeseer_tagcn.json'

#python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x '../data/pubmed/x_np.pkl' --path_edge_index '../data/pubmed/edge_index_np.pkl' --path_y '../data/pubmed/y_np.pkl' --path_save './result_distribution/pubmed_gcn.json'
#python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x '../data/pubmed/x_np.pkl' --path_edge_index '../data/pubmed/edge_index_np.pkl' --path_y '../data/pubmed/y_np.pkl' --path_save './result_distribution/pubmed_gat.json'
#python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x '../data/pubmed/x_np.pkl' --path_edge_index '../data/pubmed/edge_index_np.pkl' --path_y '../data/pubmed/y_np.pkl' --path_save './result_distribution/pubmed_graphsage.json'
#python retraining_main_distribution.py --cuda 'cuda:1' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x '../data/pubmed/x_np.pkl' --path_edge_index '../data/pubmed/edge_index_np.pkl' --path_y '../data/pubmed/y_np.pkl' --path_save './result_distribution/pubmed_tagcn.json'
